// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDklHzE2mO-KHyXg_SaLznwZyVXdrIBfCM',
    appId: '1:441746669202:web:c9fa2f1e7112ba5610304b',
    messagingSenderId: '441746669202',
    projectId: 'stylebridgeai',
    authDomain: 'stylebridgeai.firebaseapp.com',
    storageBucket: 'stylebridgeai.firebasestorage.app',
    measurementId: 'G-C98B0EF5EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX-DPtLZWe8bxRxkUDFWDieaJRiozTH4c',
    appId: '1:882420750824:android:e84cff5206cc73ec0c6c5d',
    messagingSenderId: '882420750824',
    projectId: 'fitto-63d9e',
    storageBucket: 'fitto-63d9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMzB3C0r0VEBoERydYJpQT2DrJvdvIHT4',
    appId: '1:441746669202:ios:34aea002a8e5f36d10304b',
    messagingSenderId: '441746669202',
    projectId: 'stylebridgeai',
    storageBucket: 'stylebridgeai.firebasestorage.app',
    androidClientId: '441746669202-iog4v52faariri2vidlq127rnq6tk9q4.apps.googleusercontent.com',
    iosClientId: '441746669202-hn176gjjg8cj8814k666u12tjbshnflj.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylebridgeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMzB3C0r0VEBoERydYJpQT2DrJvdvIHT4',
    appId: '1:441746669202:ios:34aea002a8e5f36d10304b',
    messagingSenderId: '441746669202',
    projectId: 'stylebridgeai',
    storageBucket: 'stylebridgeai.firebasestorage.app',
    androidClientId: '441746669202-iog4v52faariri2vidlq127rnq6tk9q4.apps.googleusercontent.com',
    iosClientId: '441746669202-hn176gjjg8cj8814k666u12tjbshnflj.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylebridgeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDklHzE2mO-KHyXg_SaLznwZyVXdrIBfCM',
    appId: '1:441746669202:web:6f0dec61132687c310304b',
    messagingSenderId: '441746669202',
    projectId: 'stylebridgeai',
    authDomain: 'stylebridgeai.firebaseapp.com',
    storageBucket: 'stylebridgeai.firebasestorage.app',
    measurementId: 'G-B82HKDX5Y9',
  );

}